version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3002/api
    volumes:
      - ./frontend:/app
    networks:
      - to-do-list

  backend:
    build:
      context: ./backend
    ports:
      - "3002:3000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=postgres  # Configuração do hostname do banco
      - DB_PORT=5432      # Porta do banco de dados
    networks:
      - to-do-list

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - to-do-list

volumes:
  postgres_data:

networks:
  to-do-list:
    driver: bridge