version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - to-do-list
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - to-do-list
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - to-do-list
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data:

networks:
  to-do-list:
    driver: bridge